name: medx
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
#  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_displaymode: ^0.6.0
  circular_countdown_timer: ^0.2.3
  image_picker: ^1.1.1
  google_maps_flutter: ^2.6.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  google_sign_in: ^6.2.1
#  change_app_package_name: ^1.2.0
  http: ^1.2.1
#  flutter_secure_storage: ^9.2.2
  flutter_keychain: ^2.5.0
  intl: ^0.19.0
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

